version: '3.4'

services:
  coze-discord-proxy:
    image: deanxv/coze-discord-proxy:latest
    container_name: coze-discord-proxy
    restart: always
    ports:
      - "7077:7077"
    volumes:
      - ./data:/app/coze-discord-proxy/data
    environment:
      - BOT_TOKEN=MTIwNzAxMDQ4NjA0MzAyNTQxOA.G-jnyh.7PP31PmJQ66-zDymohKwOc4a8nnyFzYYFrUtxw
      - GUILD_ID=1207008801916715078
      - COZE_BOT_ID=1207009406223519865
      - CHANNEL_ID=1207008801916715081
      - PROXY_SECRET=Qw12#.
      - TZ=Asia/Shanghai
