version: '3.4'

services:
  coze-discord-proxy:
    image: deanxv/coze-discord-proxy:latest
    container_name: coze-discord-proxy
    restart: always
    ports:
      - "7077:7077"
    volumes:
      - ./data:/app/coze-discord-proxy/data
    environment:
      - BOT_TOKEN=xx
      - GUILD_ID=xx
      - COZE_BOT_ID=xx
      - CHANNEL_ID=xx
      - PROXY_SECRET=xx
      - TZ=Asia/Shanghai
